// Texts of the app shell in ja / zh-CN / en.
// The launcher keys (la_*, al_*, lg_*, ...) are copied word for word from PocketRolesLauncher.ps1 (v0.5.5, lines 97-486).
// The client keys (tray.*, tip.*, quit.*, badge.*, wv2.*, files.*) come from PORT-MAP 3.13 / 4.2 and the v0.1 review.
// Chinese uses the official Among Us terms (PORT-MAP 9.3); SelfTest checks that no unofficial term slipped in.
// SPDX-License-Identifier: GPL-3.0-or-later
using System;
using System.Collections.Generic;

namespace Starpocket.Client.Core
{
    internal static class S
    {
        public static readonly Dictionary<string, Dictionary<string, string>> Table = new Dictionary<string, Dictionary<string, string>>(StringComparer.OrdinalIgnoreCase)
        {
            ["ja"] = new Dictionary<string, string>
            {
                // ---- PocketRolesLauncher.ps1 (same words)
                ["st_mod"] = "mod 用コピー",
                ["al_update"] = "アップデートを検知しました: {0} → {1}  「更新チェック / 更新」を押してください",
                ["al_rebuild"] = "PocketRoles.dll の再ビルドが必要です (「再ビルド」を押してください)",
                ["al_ok_dev"] = "最新です。「mod 付きで起動」で遊べます",
                ["al_notinstalled"] = "未インストールです。「インストール」を押してください",
                ["al_gameupdated"] = "Steam 版が更新されています ({0} → {1})。「起動」を押すとコピーを更新します",
                ["al_ok"] = "準備 OK。Steam を起動してから「起動」を押してください",
                ["game_running"] = "Among Us が起動中です。閉じてから実行してください。",
                ["err"] = "エラー: {0}",
                ["in_firstrun"] = "初回起動は BepInEx が interop を生成するため 1〜2 分かかります (黒いコンソール画面が出ますが閉じないでください)。",
                ["sync_q"] = "Steam 版が更新されています ({0} → {1})。mod 用コピーを更新しますか？ (更新しないとオンラインに入れません)",
                ["la_running"] = "Among Us はすでに起動しています。",
                ["la_steam"] = "Steam を先に起動してください。",
                ["la_notinstalled"] = "まだインストールされていません。「インストール」を押してください。",
                ["la_start"] = "mod 付きの Among Us を起動します...",
                ["la_started"] = "起動しました。左上に \"PocketRoles v...\" と表示されれば mod が有効です。",
                ["la_aegis_block"] = "Aegis が次の問題を見つけたので、起動を止めました。直してからもう一度起動してください。",
                ["la_update_q"] = "アップデートを検知しました。先に更新しますか？ (更新しないとオンラインに入れません)",
                ["la_rebuild_q"] = "PocketRoles.dll の再ビルドが必要です。今ビルドしますか？",
                ["la_vanilla"] = "Steam 版 (mod なし) を起動しました。",
                ["lg_saved"] = "前回のゲームのログを保存しました: {0}",
                ["lg_expired"] = "30 日たった過去のログ・報告 zip を {0} 件消しました",
                // ---- v0.4: ログのフォルダの大きさ・日ごとの zip（ps1 の文をそのまま）
                ["lg_zipped"] = "7 日より前のログ {0} 件を日ごとの zip にまとめました",
                ["lg_size"] = "ログ: {0}",
                ["lg_tip"] = "過去のゲームのログ (BepInEx\\PocketRoles\\logs)。7 日より前のものは日ごとの zip にまとめ、30 日たったら自動で消します",
                ["lg_big"] = "ログのフォルダが {0} になりました (2 GB 超)。30 日たったものは自動で消えます。急ぐときは「ログのフォルダを開く」から古い zip を消してください",
                // ---- v0.4: 進行ログの画面（showLog）。今までのランチャーでは窓の下のログ欄でした
                ["lg_log_title"] = "進行ログ",
                ["lg_log_sub"] = "このアプリが行ったことの記録です。新しいものが下にあります。1 MB を超えたら、次に開いた時に消します。",
                ["lg_log_none"] = "まだ記録はありません。",
                ["lg_log_more"] = "古い行は省いています。すべて見るには、この場所のファイルを開いてください。",
                ["op_notfound"] = "{0} が見つかりません: {1}",
                ["f_cfg"] = "設定ファイル",
                ["f_log"] = "ログ",
                ["f_readme"] = "説明書",
                ["v_none"] = "なし",
                // ---- v0.4: 画面なしの実行。ps1 の同じキーをそのまま写しました
                ["st_steam"] = "Steam 版 Among Us",
                ["st_bep"] = "BepInEx",
                ["st_dll"] = "PocketRoles.dll",
                ["st_interop"] = "interop (初回起動で生成)",
                ["st_client"] = "Steam クライアント",
                ["v_unknown"] = "不明",
                ["v_notfound"] = "見つかりません",
                ["v_ok"] = "OK",
                ["v_pending"] = "未生成",
                ["v_running"] = "起動中",
                ["v_stopped"] = "停止中 (起動してから遊んでください)",
                ["v_notrunning"] = "起動していません",
                ["v_needs"] = "(要更新)",
                ["log_mode"] = "モード: {0}",
                ["mode_dev"] = "開発 (ソース: {0})",
                ["mode_friend"] = "友達用 (インストーラー)",
                ["log_modded"] = "mod 用コピー: {0}",
                ["log_steam"] = "Steam 版: {0}",
                ["auto_launch"] = "自動で「プレイ」を実行します",
                // ---- v0.4: ここからは StarPocket Client で足した文です
                ["st_game"] = "Among Us",
                ["st_play"] = "プレイボタン",
                ["scan_ok"] = "OK  ",
                ["scan_warn"] = "注意",
                ["scan_stop"] = "止める",
                ["cl_unknown"] = "分からない指定があります: {0}",
                ["cl_extra"] = "指定の書き方が分かりません: {0}",
                ["cl_no_value"] = "{0} のあとに値がありません。",
                ["cl_two_modes"] = "この指定はいっしょには使えません: {0}",
                ["cl_twice"] = "同じ指定に、ちがう値が 2 つ書かれています: {0}",
                ["cl_no_launch"] = "{0} は、ゲームを起動する時だけ使えます。",
                ["cl_action_unknown"] = "--action に書けるのは install / check / report / status です ({0} は分かりません)。",
                ["cl_busy"] = "ほかの StarPocket Client が作業中です。終わるまで待ってから、もう一度お試しください。",
                ["cl_need_consent"] = "まだ利用規約とプライバシーポリシーに同意していません。この作業はインターネットにつながるので、先に StarPocket Client を開いて、最初に出る画面で答えてください（利用規約 第12条3項）。同意しなくても、アンインストールと --action status ・ --action report は使えます。",
                ["cl_running_tray"] = "StarPocket Client はすでに通知領域で動いています。",
                ["cl_play_sent"] = "動いている StarPocket Client に「プレイ」を伝えました。",
                ["cl_play_failed"] = "StarPocket Client はすでに動いていますが、「プレイ」を伝えられませんでした。画面を開いて「プレイ」を押してください。",
                ["cl_usage"] = "使い方:\r\n"
                    + "  \"StarPocket Client.exe\"                            画面を開きます\r\n"
                    + "  \"StarPocket Client.exe\" --tray                     画面を出さず、通知領域だけで動かします\r\n"
                    + "  \"StarPocket Client.exe\" --autolaunch [--windowed]  画面を出さずに、すぐゲームを起動します\r\n"
                    + "  \"StarPocket Client.exe\" --scan-only                Aegis のスキャンだけして終わります\r\n"
                    + "  \"StarPocket Client.exe\" --verify-download          配布元のファイルだけを受け取って確かめ、すぐ消します\r\n"
                    + "  \"StarPocket Client.exe\" --action install|check|report|status\r\n"
                    + "  \"StarPocket Client.exe\" --uninstall [--quiet]\r\n"
                    + "  場所と言葉: --game-dir --steam-dir --desktop-dir --language --friend\r\n"
                    + "  終了コード: 0 できました / 1 できませんでした / 2 --verify-download で値が違いました / 3 --scan-only が止める項目を見つけました",
                // ---- install / update / sync (v0.2): the launcher's words, except where it names robocopy or the
                //      Desktop shortcut this app does not make
                ["hint_continue"] = "  → 続行できます。原因を直してからもう一度押すと、この手順だけやり直します。",
                ["in_start"] = "=== インストール開始 ===",
                ["in_step1"] = "[1/5] Steam 版の Among Us をコピー...",
                ["in_step2"] = "[2/5] BepInEx {0} をダウンロード...",
                ["in_step3"] = "[3/5] PocketRoles の最新版を取得...",
                ["in_step4"] = "[4/5] 起動用ファイルを作成...",
                ["in_step5"] = "[5/5] 状態を保存...",
                ["in_steam_found"] = "Steam 版: {0}",
                ["in_steam_notfound"] = "Steam 版の Among Us が見つかりません。Among Us.exe があるフォルダを選んでください。",
                ["in_pick"] = "Among Us.exe があるフォルダ (Steam 版) を選んでください",
                ["dev_pick"] = "PocketRoles のソースのフォルダを選んでください (PocketRoles.csproj と PocketRolesLauncher.ps1 があるフォルダ)",
                ["dev_pick_bad"] = "そのフォルダは PocketRoles のソースではありません。PocketRoles.csproj と PocketRolesLauncher.ps1 の両方があるフォルダを選んでください。",
                ["dev_pick_ok"] = "ソースのフォルダを {0} にしました。次にアプリを開いたときから、このフォルダで開発モードになります。",
                ["in_copy_skip"] = "コピー済み (同じバージョン {0}) — スキップ",
                ["in_copying"] = "{0} → {1} (1 GB 前後、数分かかります)",
                ["in_copy_done"] = "コピー完了 ({0} 個をコピー、{1} 個は同じ)",
                ["in_copy_fail"] = "コピーに失敗しました ({0})。",
                ["in_copy_close"] = "ゲームや Steam を閉じてから、もう一度お試しください。",
                ["in_toolong"] = "保存先のフォルダが深すぎます。ファイルの場所が {0} 文字になり、Windows の上限 {1} 文字を超えます。もっと浅い場所 (例: C:\\PocketRoles) を選んでください。",
                ["in_nospace"] = "ドライブの空き容量が足りません。{0} 必要ですが、空きは {1} です。",
                ["in_interrupted"] = "前回の展開が途中で終わっていました。BepInEx と MOD を入れ直します。",
                ["in_dl_refused"] = "このアドレスからは取得しません（アプリが使う場所ではありません）: {0}",
                ["in_bep_skip"] = "BepInEx {0} は導入済み — スキップ",
                ["in_bep_other"] = "別のバージョンの BepInEx があります ({0})。{1} で上書きします。",
                ["in_dl"] = "ダウンロード中: {0}",
                ["in_cached"] = "ダウンロード済みのファイルを使います: {0}",
                ["in_zip_bad"] = "zip の内容が想定と違います ({1} がありません): {0}",
                ["in_bep_fail"] = "BepInEx をダウンロードできませんでした。ネット接続を確認してもう一度お試しください。",
                // ---- ダウンロードしたファイルの照合 (オーナー 2026-09-23)。中身はゲームの中で動くので、
                //      「どこから来たか」だけでなく「何が来たか」も確かめます (docs\BEPINEX-PIN.md)。
                ["in_hash_ok"] = "ダウンロードしたファイルを確かめました (BepInEx {0})",
                ["in_hash_bad"] = "ダウンロードしたファイルが、配布元の本来のものと違いました。安全のため、そのファイルは消しました。ゲームには何も入れていません。通信が途中で切れた時にも起こります。もう一度お試しください: {0}",
                ["in_hash_detail"] = "ファイルの照合: 本来の値 {0} / 届いたファイル {1}",
                ["in_bep_nohash"] = "この BepInEx ({0}) の正しいファイルの記録が、このアプリにありません。安全のため、ダウンロードも展開もしません。アプリの更新をお待ちください。",
                // ---- "--verify-download" (公開前に 1 回だけ、実機で確かめるコマンド。src\Core\BepVerifier.cs)。
                //      オーナーが読むのは小窓の 1 文だけです。ログを探しに行かせません。
                ["vd_start"] = "配布元からファイルを 1 つだけ受け取って、中身を確かめます (BepInEx {0}、約 31 MB)。ゲームのフォルダーには何も入れません。",
                ["vd_where"] = "作業用のフォルダー: {0}",
                ["vd_prog"] = "受信中... {0}%",
                ["vd_prog_mb"] = "受信中... {0} MB",
                ["vd_got"] = "受け取りました ({0} バイト): {1}",
                ["vd_ok"] = "確認できました。配布元から受け取ったファイルは、このアプリに書いてある本来のもの (BepInEx {0}) と同じでした。中身も取り出せました ({1} 個のファイル)。受け取ったファイルも、取り出したものも、すべて消しました。ゲームのフォルダーには何も入れていません。",
                ["vd_ng_hash"] = "受け取ったファイルが、このアプリに書いてある値と違いました。通信が途中で切れた時にも起こります。もう一度お試しください。それでも同じなら、配る前に作った人に知らせてください。受け取ったファイルは消しました。ゲームのフォルダーには何も入れていません。",
                ["vd_ng_zip"] = "受け取ったファイルの値は合っていましたが、中身に {0} がありませんでした。配る前に作った人に知らせてください。受け取ったファイルは消しました。ゲームのフォルダーには何も入れていません。",
                ["vd_ng_expand"] = "受け取ったファイルの値は合っていましたが、中身を取り出す途中で止まりました ({0})。ドライブの空きを確かめて、もう一度お試しください。ゲームのフォルダーには何も入れていません。",
                ["vd_ng_net"] = "配布元につながりませんでした。ファイルは受け取れていません。ネットにつながっているか確かめて、もう一度お試しください。ゲームのフォルダーには何も入れていません。",
                ["vd_ng_read"] = "ファイルを受け取る途中で止まりました。ドライブの空きとネットを確かめて、もう一度お試しください。詳しい理由は記録にあります。ゲームのフォルダーには何も入れていません。",
                ["vd_ng_space"] = "ドライブの空きが足りませんでした。150 MB 以上空けてから、もう一度お試しください。ゲームのフォルダーには何も入れていません。",
                ["vd_ng_refused"] = "配布元が、このアプリの取りに行かない場所へ案内しました。ファイルは受け取っていません。配る前に作った人に知らせてください。ゲームのフォルダーには何も入れていません。",
                ["vd_ng_temp"] = "作業用のフォルダーを作れませんでした ({0})。ゲームのフォルダーには何も入れていません。",
                ["vd_temp_taken"] = "同じ名前の別のフォルダーがすでにあります: {0}",
                ["vd_busy"] = "もう 1 つ確認が動いています。終わるまでお待ちください。ゲームのフォルダーには何も入れていません。",
                ["vd_cleaned"] = "前回の残りを片づけました: {0}",
                ["vd_prog_files"] = "展開中... {0} ファイル",
                ["vd_left"] = "作業用のファイルを消せませんでした。ここに残っています: {0}",
                ["vd_seelog"] = "詳しい記録: {0}",
                ["in_extract"] = "展開中: {0}",
                ["in_extract_done"] = "展開完了 ({0} ファイル)",
                ["in_mod_skip"] = "PocketRoles {0} は導入済み — スキップ",
                ["in_mod_local"] = "アプリと同じフォルダの zip を使います: {0}",
                ["in_mod_localdir"] = "アプリと同じフォルダに展開済みの PocketRoles を使います: {0}",
                ["in_mod_norelease"] = "GitHub にまだリリースが公開されていません。公開されたら「更新を確認」を押してください。",
                ["in_mod_fail"] = "PocketRoles を取得できませんでした。後で「更新を確認」を押すと続きから入れられます。",
                ["in_mod_done"] = "PocketRoles {0} を配置しました",
                ["in_done"] = "=== インストール完了。Steam を起動してから「プレイ」を押してください ===",
                ["in_partial"] = "=== 一部の手順が失敗しました ({0} 件)。原因を直してからもう一度押すと続きから再開します ===",
                ["up_checking"] = "GitHub で PocketRoles の最新版を確認中...",
                ["up_latest"] = "最新版: {0} / 導入済み: {1}",
                ["up_uptodate"] = "PocketRoles は最新です ({0})",
                ["up_available"] = "新しい PocketRoles {0} があります (導入済み: {1})。「アップデート」を押すと入ります。",
                ["up_available_dev"] = "新しい PocketRoles {0} があります (導入済み: {1})。「アップデート」を押すと入ります (ローカルビルドの DLL は上書きされます)。",
                // 版は同じなのに「新しいのがあります」と出ると意味が通りません。
                // 番号が同じで中身が別のファイルの時は、そう書きます。
                ["up_same_other_file"] = "入っている PocketRoles {0} は、公式に配っているファイルとは別の物です。「アップデート」を押すと、公式の物に入れ直します。",
                ["up_same_other_file_dev"] = "入っている PocketRoles {0} は、公式に配っているファイルとは別の物です。「アップデート」を押すと、公式の物に入れ直します (ローカルビルドの DLL は上書きされます)。",
                ["up_done"] = "=== 更新完了: PocketRoles {0} (設定と見た目ファイルはそのままです) ===",
                ["up_norelease"] = "GitHub にリリースがまだありません (404)。後でもう一度お試しください。",
                ["up_ratelimit"] = "GitHub の API 制限に達しました (403)。1 時間ほど待ってからもう一度お試しください。",
                ["up_api_fail"] = "GitHub に接続できませんでした: {0}  (オフラインでも遊べます)",
                ["up_asset_missing"] = "リリースに PocketRoles-<ver>.zip が見つかりません: {0}",
                ["sync_start"] = "Steam 版のゲームファイルを mod 用コピーへコピーします...",
                ["sync_done"] = "コピー完了。古い interop を削除しました。次回起動時に再生成されます (1〜2 分)。PocketRoles が新バージョンに対応していない場合は「更新を確認」を押してください。",
                ["la_sync_first"] = "Steam 版が更新されています ({0} → {1})。「更新してプレイ」を押すと、MOD 用のコピーを更新してから起動します。",
                ["al_repair"] = "MOD 用のコピーがそろっていません。「修復」を押すと直します",
                ["al_repair_mod"] = "PocketRoles のファイルが変わっています。「修復」を押すと入れ直します",
                // ---- report zip / one player's evidence (v0.3): the launcher's words on branch evidence-90d. The app has
                //      no dialog of its own - the page's report panel shows the same text.
                ["rp_creating"] = "報告 zip を作成中...",
                ["rp_done"] = "作成しました: {0}",
                ["rp_title"] = "報告 zip ができました",
                ["rp_msg"] = "デスクトップに次のファイルを作成しました:{0}{1}{0}{0}このファイルをメールに添付して送ってください。{0}  不具合: {2}{0}  要望:   {3}{0}{0}下のボタンでメールソフトが開きます (件名は入力済み)。",
                ["rp_mail_bug"] = "メールを開く (不具合)",
                ["rp_mail_req"] = "メールを開く (要望)",
                ["rp_open"] = "zip の場所を開く",
                ["rp_close"] = "閉じる",
                ["rp_subject_bug"] = "[PocketRoles] 不具合報告 v{0}",
                ["rp_subject_req"] = "[PocketRoles] 要望 v{0}",
                ["rp_body"] = "デスクトップの {0} を添付してください。{1}{1}■ 何が起きたか / 要望の内容:{1}{1}■ いつ (日時) / 部屋コード / 人数:{1}{1}■ 参加者からどう見えたか:{1}",
                ["rp_ev"] = "Aegis の証拠の記録 (直近 90 日の BAN・退出。MOD は証拠の記録を 90 日で消し、今も続いている BAN のものは、BAN が終わってから 30 日までは残します。ログは 30 日で消えるので、それより前の記録には、その記録を裏づけるログの 2 行を付けます) も {0} 件入れました。名前・部屋コード・検知の内容と、その人についての直近のログ (言い当て通知ならその人の発言の最初の 40 文字) が入ります。人を見分けるのは PUID から作ったハッシュと、記録を消すためのコードだけです (フレンドコードのハッシュ、フレンドコード・PUID そのもの、IP アドレス、ほかの人のチャットは入りません。ログの中の PUID とフレンドコードの形の文字も伏せます)。",
                ["rp_ev_none"] = "Aegis の証拠の記録はありませんでした (入れていません)。ログの中の PUID とフレンドコードの形の文字は伏せます。",
                ["rp_autodelete"] = "この zip は 30 日たつと自動で消えます (送ったあとは、すぐ消してかまいません)",
                ["ex_title"] = "ひとり分の証拠の zip",
                ["ex_prompt"] = "異議申し立ての確認のために、1 人のプレイヤーの証拠の記録だけを入れた小さな zip を作ります (ほかのプレイヤーの記録は入りません。その人の記録の検知の文に、同じ試合のほかの人の名前が入っていることはあります)。{0}{0}その人の次のどれかを入れてください:{0}・記録を消すためのコード (/cmd id の英字 16 文字){0}・フレンドコード (名前#1234){0}・証拠 ID (AEG-XXXXX)",
                ["ex_make"] = "作る",
                ["ex_cancel"] = "やめる",
                ["ex_bad"] = "入れたものが分かりません。記録を消すためのコード (英字 16 文字)、フレンドコード (名前#1234)、証拠 ID (AEG-XXXXX) のどれかを入れてください",
                ["ex_none"] = "この PC には、その人の証拠の記録がありません (証拠の記録は 90 日で消えます。今も続いている BAN の分は、BAN が終わってから 30 日まで残ります)",
                ["ex_creating"] = "その人の証拠の zip を作っています...",
                ["ex_done"] = "{0} 件の証拠の記録を入れた zip を作りました: {1}",
                ["ex_nolog"] = "{0} 件には、裏づけるログの行が見つかりませんでした (その試合のログがもうない時など。作者の照合では「ログと合わない」になります)",
                ["ex_msg"] = "デスクトップに {1} を作りました。{0}{0}入っているのは、その人の証拠の記録 {2} 件 (この PC に残っている分) と、それを裏づけるログの行、この PC の情報 (system.txt・launcher-state.json) だけです。ほかのプレイヤーの記録とログは入りません (その人の記録の検知の文に、同じ試合のほかの人の名前 — キルされた人・通報された人・投票された人など — や、BAN したモデレーターの名前が入っていることはあります)。名前・部屋コード・検知の内容は入ります。人を見分けるのは PUID のハッシュと記録を消すためのコードだけで、フレンドコードもそのハッシュも入りません (コードは、申し立てと記録を結び付けるためのもので、本人の証明にはなりません)。{0}{0}作者のメール {3} にだけ添付して送ってください。ほかの人に渡したり、公開したりしないでください (遊び方のルール 第7条)。この zip は 30 日たつと自動で消えます (送ったあとは、すぐ消してかまいません)。",
                ["ex_warn"] = "この zip は作者 ({0}) にだけ送ってください。ほかの人に渡したり、公開したりしないでください (遊び方のルール 第7条1項)。中には、その人の記録を消すためのコードと、入室制限の一覧で使う PUID のハッシュが入っています。",
                ["ex_mail"] = "メールを開く",
                ["ex_subject"] = "[PocketRoles] ひとり分の証拠 v{0}",
                ["ex_body"] = "デスクトップの {0} を添付してください。{1}{1}■ 異議申し立てをした人の名前・チケットの番号 (分かれば):{1}",
                // ---- shortcut / start with Windows / uninstall (v0.3)
                ["sc_made"] = "ショートカットを作りました: {0}",
                ["sc_fail"] = "ショートカットを作れませんでした: {0}",
                ["as_on"] = "Windows を起動した時に StarPocket Client を開きます（通知領域で待機します）。",
                ["as_off"] = "Windows を起動しても、StarPocket Client は開きません。",
                // ---- the Client's colour (v0.3.1, the owner 2026-09-23). A colour that cannot be read is never taken
                // as it is and never refused: it is moved as little as it must be, and the person is told so. These
                // two lines are what the app writes in launcher.log; the settings page says the same in its own words,
                // with the two colours shown as colours (nobody who picked from a colour wheel has seen a hex code).
                ["ac_fixed"] = "そのままだと文字が読みにくくなるので、少しだけ色を変えて使います。えらんだ色: {0} → 使う色: {1}",
                ["ac_red"] = "赤は「うまくいかなかった」を表す色なので、色あいを少しずらして使います。",
                ["un_confirm"] = "StarPocket Client をこの PC から消します。消すもの: この アプリ自身と、アプリの設定・記録（{0}）・アプリが作ったショートカット・「Windows の起動時に開く」の設定・「アプリと機能」の項目。消さないもの: Steam と Steam 版の Among Us、Aegis の記録（今までのランチャーとトレイが使います）、デスクトップに作った報告 zip（30 日で自動で消えます）。",
                ["un_keep_mod"] = "MOD 用のゲームのコピー（約 1 GB。あなたの設定と記録が入っています）は残します。いっしょに消す時はチェックを入れてください。",
                ["un_done"] = "消しました。ウィンドウを閉じます。",
                ["un_closing"] = "アンインストールします。ウィンドウを閉じてから消します。",
                ["un_partial"] = "{0} 件を消せませんでした。ゲームやエクスプローラーを閉じてから、もう一度お試しください。",
                ["un_stopped"] = "アプリの記録のフォルダーを消せなかったので、ほかのものには触っていません（何も消えていません）。もう一度お試しください: {0}",
                ["un_running"] = "StarPocket Client が起動しています。閉じてから、もう一度アンインストールしてください。",
                ["un_leftfolder"] = "このアプリのファイルは、ご自分で置いたこのフォルダーにあります。いらなければ消してください: {0}",
                ["un_title"] = "StarPocket Client をアンインストールしますか？",
                ["un_del_mod"] = "MOD 用のゲームのコピーもいっしょに消す",
                ["un_yes"] = "アンインストール",
                ["un_left"] = "残っているもの: {0}",
                ["un_selffolder"] = "動いているアプリ自身は消せないので、このフォルダーは閉じたあとに手で消してください: {0}",
                // ---- v0.4: 開発モードの「再ビルド」「更新」。ps1 の文（1756-1819）。
                //      ps1 は日本語だけを直接書いていたので、中文と English はここで新しく書きました。
                ["sdk_missing"] = ".NET SDK が見つかりません: {0}",
                ["dev_only"] = "この機能は開発モードでだけ使えます（設定 → PocketRoles → 開発 で切り替えた時、または PocketRoles.csproj のあるフォルダーから起動した時）。",
                // ---- v1.1: 開発用への切り替え（設定 → PocketRoles → 開発）と、いま入っている DLL がどちらか（src\Core\DevSource.cs・ModOrigin.cs）
                ["dev_nofolder"] = "開発用の置き場所が見つかりません（デスクトップの PocketRoles.lnk の先、または デスクトップ\\HostRoles に PocketRoles.csproj と PocketRolesLauncher.ps1 の両方があること）。",
                ["dev_switch_on"] = "開発用に切り替えます。StarPocket Client を開き直します。",
                ["dev_switch_off"] = "配布用（友達モード）に戻します。StarPocket Client を開き直します。",
                ["origin_dev"] = "開発ビルド（{0} に再ビルド）",
                ["origin_release"] = "配布版 {0}（{1} に導入）",
                ["origin_unknown"] = "このクライアント以外が入れたもの（今までのランチャーの再ビルドなど）",
                ["dev_building"] = "PocketRoles をビルドしています (1〜2 分)...",
                ["dev_build_done"] = "ビルド成功。PocketRoles.dll を BepInEx\\plugins に配置しました。",
                ["dev_build_ok"] = "ビルドが終わりました。",
                ["dev_build_failed"] = "ビルドに失敗しました。",
                ["dev_build_timeout"] = "ビルドが {0} 分たっても終わらなかったので、止めました。",
                ["dev_build_failed_exit"] = "ビルド失敗 (exit {0})。ゲームの API が変わった可能性があります。",
                ["dev_build_ask"] = "エラー内容を添えて「PocketRoles をアップデート対応して」と Claude に依頼してください。",
                ["dev_need_steam"] = "Steam を起動してから更新してください (interop 生成にゲームの起動が必要です)。",
                ["dev_up_start"] = "=== 更新開始 ===",
                ["dev_up_1"] = "[1/4] Steam 版のゲームファイルを mod 用コピーへコピー...",
                ["dev_up_2"] = "[2/4] 古い interop / cache を削除...",
                ["dev_up_3"] = "[3/4] ゲームを起動して interop を生成します (1〜3 分。自動で閉じます)...",
                ["dev_up_4"] = "[4/4] PocketRoles を再ビルド...",
                ["dev_interop_failed"] = "interop が生成されませんでした。BepInEx\\LogOutput.log を確認してください。",
                ["dev_interop_ok"] = "interop 生成完了。",
                ["dev_up_done"] = "=== 更新完了。「mod 付きで起動」で遊べます ===",
                // ---- StarPocket Client
                ["tray.open"] = "開く",
                ["tray.play"] = "プレイ",
                ["tray.aegis"] = "Aegis の状態",
                ["tray.rescan"] = "もう一度スキャン",
                ["tray.quit"] = "終了",
                ["tip.idle"] = "StarPocket Client — Aegis 待機中",
                ["tip.watching"] = "StarPocket Client — Aegis 監視中 · 検知 {0} · 退出 {1}",
                ["tip.off"] = "StarPocket Client — Aegis 停止中",
                ["tip.serious"] = "StarPocket Client — Aegis が問題を見つけました",
                ["tip.oldtray"] = "StarPocket Client — 古い Aegis トレイが見張っています",
                ["tray.stillRunning"] = "画面右下の通知領域で動き続けています。終わる時はアイコンを右クリックして「終了」を押してください。",
                ["quit.confirm"] = "ゲームが終わるまでの Aegis の見張りも止まります。終了しますか？",
                ["badge.serious"] = "Aegis が問題を見つけました",
                ["badge.kicked"] = "Aegis がプレイヤーを退出させました",
                ["wv2.head"] = "WebView2 ランタイムを入れてください",
                ["wv2.body"] = "画面の表示に使う Microsoft の部品です。開いたページで「Evergreen Bootstrapper」をダウンロードし、そのファイルを開いて入れてから、「もう一度確かめる」を押してください。",
                ["wv2.old"] = "今までのランチャー（PocketRoles Launcher.cmd）も使えます。",
                ["wv2.open"] = "ダウンロードのページを開く",
                ["wv2.retry"] = "もう一度確かめる",
                ["wv2.notyet"] = "まだ見つかりません。入れ終わってから、もう一度押してください。",
                ["wv2.close"] = "閉じる",
                ["files.missing"] = "StarPocket Client のファイルが足りません。zip の中身をすべて同じフォルダーに展開してから開いてください（exe だけをコピーしても動きません）。",
                ["ui.failed"] = "画面を開けませんでした: {0}",
                // ---- v1.3: アイコンの画像（src\Core\ProfileImage.cs）
                ["av_pick"] = "アイコンにする画像を選んでください",
                ["av_filter"] = "画像 (*.png;*.jpg;*.jpeg;*.ico;*.bmp;*.gif)|*.png;*.jpg;*.jpeg;*.ico;*.bmp;*.gif",
                ["av_toobig"] = "その画像は大きすぎます（{0}）。20 MB までにしてください",
                ["av_toomany"] = "その画像は画素が多すぎます（{0}×{1}）。3000 万画素までにしてください",
                ["av_unreadable"] = "その画像は読めませんでした（壊れているか、対応していない形式です）。元の絵のままにします",
                ["av_webp"] = "この版では WebP は読めません。PNG か JPG にしてから選んでください",
                ["av_nofile"] = "そのファイルは開けませんでした（場所が読めないか、もう無いようです）",
                ["av_write"] = "画像の写しを保存できませんでした: {0}",
                ["av_broken"] = "保存してあったアイコンの画像が読めなかったので、元の絵に戻しました",
                ["av_set"] = "アイコンの画像を取り込みました（{0}×{1} → 256×256）",
                ["av_cleared"] = "アイコンの画像をやめて、元の絵に戻しました",
            },
            ["zh-CN"] = new Dictionary<string, string>
            {
                ["st_mod"] = "mod 副本",
                ["al_update"] = "检测到游戏更新: {0} → {1}  请点击“检查 / 更新游戏”",
                ["al_rebuild"] = "需要重新编译 PocketRoles.dll (请点击“仅重新编译”)",
                ["al_ok_dev"] = "已是最新。点击“带 mod 启动”开始游戏",
                ["al_notinstalled"] = "尚未安装。请点击“安装”",
                ["al_gameupdated"] = "Steam 版已更新 ({0} → {1})。点击“启动”时会更新副本",
                ["al_ok"] = "准备就绪。请先启动 Steam，再点击“启动”",
                ["game_running"] = "Among Us 正在运行。请关闭后再试。",
                ["err"] = "错误: {0}",
                ["in_firstrun"] = "首次启动时 BepInEx 需要生成 interop，约 1〜2 分钟 (会出现黑色控制台窗口，请不要关闭)。",
                ["sync_q"] = "Steam 版已更新 ({0} → {1})。要更新 mod 副本吗？(不更新将无法进入在线游戏)",
                ["la_running"] = "Among Us 已在运行。",
                ["la_steam"] = "请先启动 Steam。",
                ["la_notinstalled"] = "尚未安装。请点击“安装”。",
                ["la_start"] = "正在启动带 mod 的 Among Us...",
                ["la_started"] = "已启动。左上角显示 \"PocketRoles v...\" 即表示 mod 生效。",
                ["la_aegis_block"] = "Aegis 发现了以下问题，已阻止启动。请处理后再启动。",
                ["la_update_q"] = "检测到游戏更新。要先更新吗？(不更新将无法进入在线游戏)",
                ["la_rebuild_q"] = "需要重新编译 PocketRoles.dll。现在编译吗？",
                ["la_vanilla"] = "已启动 Steam 原版 (无 mod)。",
                ["lg_saved"] = "已保存上次游戏的日志: {0}",
                ["lg_expired"] = "已删除 {0} 个超过 30 天的旧日志・报告 zip",
                ["lg_zipped"] = "已将 {0} 个超过 7 天的日志按天归入 zip",
                ["lg_size"] = "日志: {0}",
                ["lg_tip"] = "以往游戏的日志 (BepInEx\\PocketRoles\\logs)。超过 7 天的会按天归入 zip，30 天后自动删除",
                ["lg_big"] = "日志文件夹已达 {0} (超过 2 GB)。超过 30 天的会自动删除；着急时请通过“打开日志文件夹”删除旧的 zip",
                ["lg_log_title"] = "运行日志",
                ["lg_log_sub"] = "这个应用做过什么的记录。新的在下面。超过 1 MB 时，下次打开会删除。",
                ["lg_log_none"] = "还没有记录。",
                ["lg_log_more"] = "已省略较旧的行。要看全部，请打开这个位置的文件。",
                ["op_notfound"] = "未找到{0}: {1}",
                ["f_cfg"] = "设置文件",
                ["f_log"] = "日志",
                ["f_readme"] = "说明书",
                ["v_none"] = "无",
                // ---- v0.4: 画面なしの実行（ps1 の同じキー）
                ["st_steam"] = "Steam 版 Among Us",
                ["st_bep"] = "BepInEx",
                ["st_dll"] = "PocketRoles.dll",
                ["st_interop"] = "interop (首次启动时生成)",
                ["st_client"] = "Steam 客户端",
                ["v_unknown"] = "未知",
                ["v_notfound"] = "未找到",
                ["v_ok"] = "OK",
                ["v_pending"] = "未生成",
                ["v_running"] = "运行中",
                ["v_stopped"] = "未运行 (请先启动 Steam)",
                ["v_notrunning"] = "未运行",
                ["v_needs"] = "(需更新)",
                ["log_mode"] = "模式: {0}",
                ["mode_dev"] = "开发 (源码: {0})",
                ["mode_friend"] = "好友版 (安装器)",
                ["log_modded"] = "mod 副本: {0}",
                ["log_steam"] = "Steam 版: {0}",
                ["auto_launch"] = "将自动执行“开始游戏”",
                // ---- v0.4: StarPocket Client 新增
                ["st_game"] = "Among Us",
                ["st_play"] = "开始按钮",
                ["scan_ok"] = "OK  ",
                ["scan_warn"] = "注意",
                ["scan_stop"] = "阻止",
                ["cl_unknown"] = "有无法识别的指定: {0}",
                ["cl_extra"] = "无法识别这种写法: {0}",
                ["cl_no_value"] = "{0} 后面没有值。",
                ["cl_two_modes"] = "这些指定不能一起使用: {0}",
                ["cl_twice"] = "同一个指定写了两个不同的值: {0}",
                ["cl_no_launch"] = "{0} 只能在启动游戏时使用。",
                ["cl_action_unknown"] = "--action 只能写 install / check / report / status ({0} 无法识别)。",
                ["cl_busy"] = "另一个 StarPocket Client 正在处理。请等它结束后再试一次。",
                ["cl_need_consent"] = "您还没有同意用户条款与隐私政策。此操作会连接互联网，请先打开 StarPocket Client，在最初出现的画面上作答（用户条款 第12条第3款）。即使不同意，卸载与 --action status ・ --action report 仍然可以使用。",
                ["cl_running_tray"] = "StarPocket Client 已经在通知区域运行。",
                ["cl_play_sent"] = "已通知正在运行的 StarPocket Client“开始游戏”。",
                ["cl_play_failed"] = "StarPocket Client 已经在运行，但无法通知它“开始游戏”。请打开窗口并点击“开始游戏”。",
                ["cl_usage"] = "用法:\r\n"
                    + "  \"StarPocket Client.exe\"                            打开窗口\r\n"
                    + "  \"StarPocket Client.exe\" --tray                     不显示窗口，只在通知区域运行\r\n"
                    + "  \"StarPocket Client.exe\" --autolaunch [--windowed]  不显示窗口，立即启动游戏\r\n"
                    + "  \"StarPocket Client.exe\" --scan-only                只做一次 Aegis 扫描然后结束\r\n"
                    + "  \"StarPocket Client.exe\" --verify-download          只接收发布方的文件进行核对，然后立即删除\r\n"
                    + "  \"StarPocket Client.exe\" --action install|check|report|status\r\n"
                    + "  \"StarPocket Client.exe\" --uninstall [--quiet]\r\n"
                    + "  位置和语言: --game-dir --steam-dir --desktop-dir --language --friend\r\n"
                    + "  退出代码: 0 成功 / 1 失败 / 2 --verify-download 核对不一致 / 3 --scan-only 发现了阻止启动的项目",
                ["hint_continue"] = "  → 可以继续。解决原因后再点一次，只会重做这一步。",
                ["in_start"] = "=== 开始安装 ===",
                ["in_step1"] = "[1/5] 复制 Steam 版 Among Us...",
                ["in_step2"] = "[2/5] 下载 BepInEx {0}...",
                ["in_step3"] = "[3/5] 获取最新的 PocketRoles...",
                ["in_step4"] = "[4/5] 创建启动文件...",
                ["in_step5"] = "[5/5] 保存状态...",
                ["in_steam_found"] = "Steam 版: {0}",
                ["in_steam_notfound"] = "未找到 Steam 版 Among Us。请选择包含 Among Us.exe 的文件夹。",
                ["in_pick"] = "请选择包含 Among Us.exe 的文件夹 (Steam 版)",
                ["dev_pick"] = "请选择 PocketRoles 的源代码文件夹 (含 PocketRoles.csproj 与 PocketRolesLauncher.ps1 的文件夹)",
                ["dev_pick_bad"] = "该文件夹不是 PocketRoles 的源代码。请选择同时含有 PocketRoles.csproj 与 PocketRolesLauncher.ps1 的文件夹。",
                ["dev_pick_ok"] = "已把源代码文件夹设为 {0}。下次打开应用时，将以该文件夹进入开发模式。",
                ["in_copy_skip"] = "已复制 (版本相同 {0}) — 跳过",
                ["in_copying"] = "{0} → {1} (约 1 GB，需要几分钟)",
                ["in_copy_done"] = "复制完成 (复制了 {0} 个，{1} 个相同)",
                ["in_copy_fail"] = "复制失败 ({0})。",
                ["in_copy_close"] = "请关闭游戏和 Steam 后重试。",
                ["in_toolong"] = "所选文件夹层级过深。文件路径将达到 {0} 个字符，超过 Windows 的上限 {1} 个字符。请选择更浅的位置 (例如 C:\\PocketRoles)。",
                ["in_nospace"] = "驱动器空间不足。需要 {0}，但只剩 {1}。",
                ["in_interrupted"] = "上次解压未完成。将重新安装 BepInEx 和模组。",
                ["in_dl_refused"] = "不会从这个地址获取（不是应用使用的位置）: {0}",
                ["in_bep_skip"] = "BepInEx {0} 已安装 — 跳过",
                ["in_bep_other"] = "存在其他版本的 BepInEx ({0})。将用 {1} 覆盖。",
                ["in_dl"] = "正在下载: {0}",
                ["in_cached"] = "使用已下载的文件: {0}",
                ["in_zip_bad"] = "zip 内容不符 (缺少 {1}): {0}",
                ["in_bep_fail"] = "无法下载 BepInEx。请检查网络后重试。",
                ["in_hash_ok"] = "已核对下载的文件 (BepInEx {0})",
                ["in_hash_bad"] = "下载的文件与发布方的原文件不一致。为安全起见已删除该文件，没有向游戏里放入任何内容。网络中途断开时也会这样。请再试一次: {0}",
                ["in_hash_detail"] = "文件核对: 应为 {0} / 收到 {1}",
                ["in_bep_nohash"] = "本应用没有记录这个 BepInEx ({0}) 的正确文件。为安全起见，不会下载也不会解压。请等待应用更新。",
                // ---- "--verify-download" (src\Core\BepVerifier.cs)
                ["vd_start"] = "只从发布方接收一个文件并核对内容 (BepInEx {0}，约 31 MB)。不会向游戏文件夹放入任何内容。",
                ["vd_where"] = "工作文件夹: {0}",
                ["vd_prog"] = "接收中... {0}%",
                ["vd_prog_mb"] = "接收中... {0} MB",
                ["vd_got"] = "已接收 ({0} 字节): {1}",
                ["vd_ok"] = "核对成功。从发布方接收的文件与本应用记录的原文件 (BepInEx {0}) 一致。内容也能正常解压 ({1} 个文件)。接收的文件和解压出来的内容都已删除。没有向游戏文件夹放入任何内容。",
                ["vd_ng_hash"] = "接收的文件与本应用记录的值不一致。网络中途断开时也会这样。请再试一次。如果仍然相同，请在发布前告知作者。接收的文件已删除。没有向游戏文件夹放入任何内容。",
                ["vd_ng_zip"] = "接收的文件的值是对的，但内容里没有 {0}。请在发布前告知作者。接收的文件已删除。没有向游戏文件夹放入任何内容。",
                ["vd_ng_expand"] = "接收的文件的值是对的，但解压中途停止了 ({0})。请确认磁盘剩余空间后再试一次。没有向游戏文件夹放入任何内容。",
                ["vd_ng_net"] = "无法连接发布方。没有接收到文件。请确认网络连接后再试一次。没有向游戏文件夹放入任何内容。",
                ["vd_ng_read"] = "接收文件的过程中中断了。请确认磁盘剩余空间和网络连接后再试一次。详细原因在记录里。没有向游戏文件夹放入任何内容。",
                ["vd_ng_space"] = "磁盘剩余空间不足。请腾出 150 MB 以上后再试一次。没有向游戏文件夹放入任何内容。",
                ["vd_ng_refused"] = "发布方把请求指向了本应用不会访问的地址。没有接收到文件。请在发布前告知作者。没有向游戏文件夹放入任何内容。",
                ["vd_ng_temp"] = "无法创建工作文件夹 ({0})。没有向游戏文件夹放入任何内容。",
                ["vd_temp_taken"] = "同名的其他文件夹已经存在: {0}",
                ["vd_busy"] = "已有另一个核对正在进行。请等它结束。没有向游戏文件夹放入任何内容。",
                ["vd_cleaned"] = "已清理上次剩下的内容: {0}",
                ["vd_prog_files"] = "正在解压... {0} 个文件",
                ["vd_left"] = "无法删除工作用的文件。它们留在这里: {0}",
                ["vd_seelog"] = "详细记录: {0}",
                ["in_extract"] = "正在解压: {0}",
                ["in_extract_done"] = "解压完成 ({0} 个文件)",
                ["in_mod_skip"] = "PocketRoles {0} 已安装 — 跳过",
                ["in_mod_local"] = "使用应用同目录下的 zip: {0}",
                ["in_mod_localdir"] = "使用应用同目录下已解压的 PocketRoles: {0}",
                ["in_mod_norelease"] = "GitHub 上尚未发布版本。发布后请点击“检查更新”。",
                ["in_mod_fail"] = "无法获取 PocketRoles。稍后点击“检查更新”即可继续安装。",
                ["in_mod_done"] = "已安装 PocketRoles {0}",
                ["in_done"] = "=== 安装完成。请先启动 Steam，再点击“开始游戏” ===",
                ["in_partial"] = "=== 有 {0} 个步骤失败。解决原因后再点一次即可从中断处继续 ===",
                ["up_checking"] = "正在从 GitHub 检查 PocketRoles 的最新版本...",
                ["up_latest"] = "最新: {0} / 已安装: {1}",
                ["up_uptodate"] = "PocketRoles 已是最新 ({0})",
                ["up_available"] = "有新版本 PocketRoles {0} (已安装: {1})。按“更新”即可安装。",
                ["up_available_dev"] = "有新版本 PocketRoles {0} (已安装: {1})。按“更新”即可安装 (本地编译的 DLL 会被覆盖)。",
                ["up_same_other_file"] = "已安装的 PocketRoles {0} 与官方发布的文件不是同一个。按“更新”会重新安装官方的版本。",
                ["up_same_other_file_dev"] = "已安装的 PocketRoles {0} 与官方发布的文件不是同一个。按“更新”会重新安装官方的版本 (本地编译的 DLL 会被覆盖)。",
                ["up_done"] = "=== 更新完成: PocketRoles {0} (设置和外观文件保持不变) ===",
                ["up_norelease"] = "GitHub 上还没有发布版本 (404)。请稍后再试。",
                ["up_ratelimit"] = "达到 GitHub API 限制 (403)。请等待约 1 小时后重试。",
                ["up_api_fail"] = "无法连接 GitHub: {0}  (离线也可以游戏)",
                ["up_asset_missing"] = "发布中未找到 PocketRoles-<ver>.zip: {0}",
                ["sync_start"] = "正在把 Steam 版的游戏文件复制到 mod 副本...",
                ["sync_done"] = "复制完成，已删除旧的 interop。下次启动时会重新生成 (1〜2 分钟)。如果 PocketRoles 不支持新版本，请点击“检查更新”。",
                ["la_sync_first"] = "Steam 版已更新 ({0} → {1})。按“更新并开始游戏”会先更新 mod 副本，再启动。",
                ["al_repair"] = "mod 副本不完整。按“修复”即可修好",
                ["al_repair_mod"] = "PocketRoles 的文件有变化。按“修复”会重新安装",
                ["rp_creating"] = "正在生成报告 zip...",
                ["rp_done"] = "已生成: {0}",
                ["rp_title"] = "报告 zip 已生成",
                ["rp_msg"] = "已在桌面生成以下文件:{0}{1}{0}{0}请把该文件作为附件用邮件发送。{0}  问题: {2}{0}  建议: {3}{0}{0}点击下方按钮会打开邮件软件 (主题已填好)。",
                ["rp_mail_bug"] = "打开邮件 (问题)",
                ["rp_mail_req"] = "打开邮件 (建议)",
                ["rp_open"] = "打开 zip 所在位置",
                ["rp_close"] = "关闭",
                ["rp_subject_bug"] = "[PocketRoles] 问题报告 v{0}",
                ["rp_subject_req"] = "[PocketRoles] 功能建议 v{0}",
                ["rp_body"] = "请附上桌面上的 {0}。{1}{1}■ 发生了什么 / 建议内容:{1}{1}■ 时间 / 房间代码 / 人数:{1}{1}■ 其他玩家看到了什么:{1}",
                ["rp_ev"] = "也放入了 {0} 条 Aegis 证据记录 (最近 90 天的封禁・移出。模组的证据记录 90 天后删除，仍在生效的封禁的记录至少保留到封禁结束后 30 天。日志 30 天后删除，所以更早的记录会附上证明该记录的 2 行日志)。包含名字・房间代码・检测内容，以及有关此人的最近日志 (点中提示时为此人发言的前 40 个字)。识别玩家只用由 PUID 生成的哈希和删除记录用的代码 (不包含好友编号的哈希、好友编号・PUID 本身、IP 地址和其他人的聊天；日志中的 PUID 和好友编号形式的文字也会隐去)。",
                // 好友编号 (the official term), not the launcher's 好友代码 in this one line (PORT-MAP 9.3: terms are the
                // one thing the port corrects; the launcher's own rp_ev uses 好友编号 two lines above)
                ["rp_ev_none"] = "没有 Aegis 证据记录 (未放入)。日志中的 PUID 和好友编号形式的文字会隐去。",
                ["rp_autodelete"] = "此 zip 在 30 天后会自动删除 (发送后可以立即删除)",
                ["ex_title"] = "单人证据 zip",
                ["ex_prompt"] = "为了核对申诉，生成一个只包含一名玩家的证据记录的小 zip (不包含其他玩家的记录；此人记录的检测内容中可能出现同一局其他玩家的名字)。{0}{0}请输入此人的以下任意一项:{0}・删除记录用的代码 (/cmd id 显示的 16 个英文字母){0}・好友编号 (名字#1234){0}・证据 ID (AEG-XXXXX)",
                ["ex_make"] = "生成",
                ["ex_cancel"] = "取消",
                ["ex_bad"] = "无法识别输入的内容。请输入删除记录用的代码 (16 个英文字母)、好友编号 (名字#1234) 或证据 ID (AEG-XXXXX) 中的一项",
                ["ex_none"] = "这台电脑上没有此人的证据记录 (证据记录 90 天后删除；仍在生效的封禁的记录保留到封禁结束后 30 天)",
                ["ex_creating"] = "正在生成此人的证据 zip...",
                ["ex_done"] = "已生成包含 {0} 条证据记录的 zip: {1}",
                ["ex_nolog"] = "其中 {0} 条没有找到证明该记录的日志行 (例如该局的日志已不存在。作者核对时会显示“与日志不符”)",
                ["ex_msg"] = "已在桌面生成 {1}。{0}{0}其中只有此人的 {2} 条证据记录 (这台电脑上保留的)、证明这些记录的日志行，以及这台电脑的信息 (system.txt・launcher-state.json)。不包含其他玩家的记录和日志 (此人记录的检测内容中，可能出现同一局其他玩家的名字 — 被击杀的人、被报告的人、被投票的人等 — 或执行封禁的管理员的名字)。包含名字・房间代码・检测内容。识别玩家只用 PUID 的哈希和删除记录用的代码，不包含好友编号及其哈希 (该代码用于把申诉与记录对应起来，并不能证明是本人)。{0}{0}请只作为附件发到作者的邮箱 {3}，不要转给他人或公开 (游玩规则 第7条)。此 zip 在 30 天后会自动删除 (发送后可以立即删除)。",
                ["ex_warn"] = "此 zip 请只发给作者 ({0})，不要转给他人或公开 (游玩规则 第7条第1项)。其中包含此人删除记录用的代码，以及入室限制名单使用的 PUID 哈希。",
                ["ex_mail"] = "打开邮件",
                ["ex_subject"] = "[PocketRoles] 单人证据 v{0}",
                ["ex_body"] = "请附上桌面上的 {0}。{1}{1}■ 提出申诉的人的名字・工单编号 (如果知道):{1}",
                ["sc_made"] = "已创建快捷方式: {0}",
                ["sc_fail"] = "无法创建快捷方式: {0}",
                ["as_on"] = "开机时会打开 StarPocket Client（在通知区域待机）。",
                ["as_off"] = "开机时不会打开 StarPocket Client。",
                ["ac_fixed"] = "就这样文字会变得不好辨认，因此稍微调整了颜色再使用。所选颜色: {0} → 实际使用: {1}",
                ["ac_red"] = "红色表示“没有成功”，因此把色相稍微移开一点再使用。",
                ["un_confirm"] = "将从这台电脑上删除 StarPocket Client。会删除: 应用本身、应用的设置和记录（{0}）、应用创建的快捷方式、“开机时打开”的设置、“应用和功能”中的条目。不会删除: Steam 和 Steam 版 Among Us、Aegis 的记录（原来的启动器和托盘要用）、桌面上的报告 zip（30 天后自动删除）。",
                ["un_keep_mod"] = "模组用的游戏副本（约 1 GB，其中有你的设置和记录）会保留。要一起删除请勾选。",
                ["un_done"] = "已删除。窗口将关闭。",
                ["un_closing"] = "开始卸载。窗口关闭后进行删除。",
                ["un_partial"] = "有 {0} 项无法删除。请关闭游戏和资源管理器后重试。",
                ["un_stopped"] = "无法删除应用的记录文件夹，因此没有动其他任何内容（什么都没有删除）。请重试: {0}",
                ["un_running"] = "StarPocket Client 正在运行。请关闭后再卸载。",
                ["un_leftfolder"] = "这个应用的文件在你自己放置的这个文件夹里。不需要的话请自行删除: {0}",
                ["un_title"] = "要卸载 StarPocket Client 吗？",
                ["un_del_mod"] = "同时删除模组用的游戏副本",
                ["un_yes"] = "卸载",
                ["un_left"] = "保留的内容: {0}",
                ["un_selffolder"] = "正在运行的应用无法删除自己，请在关闭后手动删除此文件夹: {0}",
                // ---- v0.4: 开发模式的“仅重新编译”“检查 / 更新”
                ["sdk_missing"] = "未找到 .NET SDK: {0}",
                ["dev_only"] = "这个功能只能在开发模式下使用（在 设置 → PocketRoles → 开发 中切换后，或从含有 PocketRoles.csproj 的文件夹启动时）。",
                // ---- v1.1: 切换到开发版（设置 → PocketRoles → 开发），以及现在装的是哪个 DLL
                ["dev_nofolder"] = "找不到开发用的存放位置（桌面上 PocketRoles.lnk 指向的文件夹，或 桌面\\HostRoles，需要同时有 PocketRoles.csproj 和 PocketRolesLauncher.ps1）。",
                ["dev_switch_on"] = "切换到开发版。StarPocket Client 将重新打开。",
                ["dev_switch_off"] = "切回发布版（朋友模式）。StarPocket Client 将重新打开。",
                ["origin_dev"] = "开发版编译（{0} 重新编译）",
                ["origin_release"] = "发布版 {0}（{1} 安装）",
                ["origin_unknown"] = "不是这个客户端放进去的（例如用原来的启动器重新编译）",
                ["dev_building"] = "正在编译 PocketRoles (1〜2 分钟)...",
                ["dev_build_done"] = "编译成功。已把 PocketRoles.dll 放入 BepInEx\\plugins。",
                ["dev_build_ok"] = "编译已完成。",
                ["dev_build_failed"] = "编译失败。",
                ["dev_build_timeout"] = "编译过了 {0} 分钟还没有结束，已经停止。",
                ["dev_build_failed_exit"] = "编译失败 (exit {0})。游戏的 API 可能已经改变。",
                ["dev_build_ask"] = "请附上错误内容，对 Claude 说“请让 PocketRoles 适配新版本”。",
                ["dev_need_steam"] = "请先启动 Steam 再更新 (生成 interop 需要启动游戏)。",
                ["dev_up_start"] = "=== 开始更新 ===",
                ["dev_up_1"] = "[1/4] 把 Steam 版的游戏文件复制到 mod 副本...",
                ["dev_up_2"] = "[2/4] 删除旧的 interop / cache...",
                ["dev_up_3"] = "[3/4] 启动游戏以生成 interop (1〜3 分钟，会自动关闭)...",
                ["dev_up_4"] = "[4/4] 重新编译 PocketRoles...",
                ["dev_interop_failed"] = "没有生成 interop。请查看 BepInEx\\LogOutput.log。",
                ["dev_interop_ok"] = "interop 生成完成。",
                ["dev_up_done"] = "=== 更新完成。可以用“带 mod 启动”开始游戏 ===",
                ["tray.open"] = "打开",
                ["tray.play"] = "开始游戏",
                ["tray.aegis"] = "Aegis 状态",
                ["tray.rescan"] = "重新扫描",
                ["tray.quit"] = "退出",
                ["tip.idle"] = "StarPocket Client — Aegis 待机中",
                ["tip.watching"] = "StarPocket Client — Aegis 监视中 · 检测 {0} · 移出 {1}",
                ["tip.off"] = "StarPocket Client — Aegis 已停止",
                ["tip.serious"] = "StarPocket Client — Aegis 发现了问题",
                ["tip.oldtray"] = "StarPocket Client — 旧版 Aegis 托盘正在监视",
                ["tray.stillRunning"] = "仍在屏幕右下角的通知区域运行。要退出，请右键点击图标并选择“退出”。",
                ["quit.confirm"] = "退出后，Aegis 将不再监视本局游戏。要退出吗？",
                ["badge.serious"] = "Aegis 发现了问题",
                ["badge.kicked"] = "Aegis 已移出玩家",
                ["wv2.head"] = "请安装 WebView2 运行时",
                ["wv2.body"] = "这是显示界面所用的 Microsoft 组件。请在打开的页面中下载“Evergreen Bootstrapper”，运行下载的文件完成安装后，点击“重新检查”。",
                ["wv2.old"] = "也可以继续使用原来的启动器（PocketRoles Launcher.cmd）。",
                ["wv2.open"] = "打开下载页面",
                ["wv2.retry"] = "重新检查",
                ["wv2.notyet"] = "仍未找到。请在安装完成后再点击一次。",
                ["wv2.close"] = "关闭",
                ["files.missing"] = "StarPocket Client 的文件不全。请把 zip 中的所有文件解压到同一个文件夹后再打开（只复制 exe 无法运行）。",
                ["ui.failed"] = "无法打开界面：{0}",
                // ---- v1.3: 头像图片（src\Core\ProfileImage.cs）
                ["av_pick"] = "请选择用作头像的图片",
                ["av_filter"] = "图片 (*.png;*.jpg;*.jpeg;*.ico;*.bmp;*.gif)|*.png;*.jpg;*.jpeg;*.ico;*.bmp;*.gif",
                ["av_toobig"] = "这张图片太大了（{0}）。请使用 20 MB 以内的图片",
                ["av_toomany"] = "这张图片的像素太多了（{0}×{1}）。请使用 3000 万像素以内的图片",
                ["av_unreadable"] = "无法读取这张图片（文件已损坏，或格式不受支持）。头像保持原来的图案",
                ["av_webp"] = "此版本无法读取 WebP。请先转换为 PNG 或 JPG 再选择",
                ["av_nofile"] = "无法打开该文件（位置无法读取，或文件已不存在）",
                ["av_write"] = "无法保存图片副本：{0}",
                ["av_broken"] = "保存的头像图片无法读取，已恢复为原来的图案",
                ["av_set"] = "已导入头像图片（{0}×{1} → 256×256）",
                ["av_cleared"] = "已取消头像图片，恢复为原来的图案",
            },
            ["en"] = new Dictionary<string, string>
            {
                ["st_mod"] = "Modded copy",
                ["al_update"] = "Game update detected: {0} → {1}  Press \"Check / update game\"",
                ["al_rebuild"] = "PocketRoles.dll needs a rebuild (press \"Rebuild only\")",
                ["al_ok_dev"] = "Up to date. Press \"Launch with mod\" to play",
                ["al_notinstalled"] = "Not installed yet. Press \"Install\"",
                ["al_gameupdated"] = "Steam version updated ({0} → {1}). \"Launch\" will refresh the copy",
                ["al_ok"] = "Ready. Start Steam, then press \"Launch\"",
                ["game_running"] = "Among Us is running. Close it first.",
                ["err"] = "Error: {0}",
                ["in_firstrun"] = "The first launch takes 1-2 minutes while BepInEx generates interop assemblies (a black console window appears — do not close it).",
                ["sync_q"] = "The Steam version was updated ({0} → {1}). Refresh the modded copy? (required to play online)",
                ["la_running"] = "Among Us is already running.",
                ["la_steam"] = "Please start Steam first.",
                ["la_notinstalled"] = "Not installed yet. Press \"Install\".",
                ["la_start"] = "Launching Among Us with the mod...",
                ["la_started"] = "Launched. The mod is active when \"PocketRoles v...\" appears at the top-left.",
                ["la_aegis_block"] = "Aegis found the problems below and stopped the start. Fix them, then start again.",
                ["la_update_q"] = "A game update was detected. Update first? (required to play online)",
                ["la_rebuild_q"] = "PocketRoles.dll needs a rebuild. Build now?",
                ["la_vanilla"] = "Launched the Steam version (no mod).",
                ["lg_saved"] = "Saved the log of the previous game: {0}",
                ["lg_expired"] = "Deleted {0} past log(s) / report zip(s) older than 30 days",
                ["lg_zipped"] = "Moved {0} log(s) older than 7 days into daily zips",
                ["lg_size"] = "Logs: {0}",
                ["lg_tip"] = "Logs of past games (BepInEx\\PocketRoles\\logs). Logs older than 7 days go into daily zips; they are deleted after 30 days",
                ["lg_big"] = "The logs folder has reached {0} (over 2 GB). Logs are deleted after 30 days; to free space now, delete old zips via \"Open logs folder\"",
                ["lg_log_title"] = "Task log",
                ["lg_log_sub"] = "A record of what this app has done. The newest is at the bottom. Once it passes 1 MB it is deleted the next time the app opens.",
                ["lg_log_none"] = "Nothing recorded yet.",
                ["lg_log_more"] = "Older lines are left out. To see them all, open the file at this location.",
                ["op_notfound"] = "{0} not found: {1}",
                ["f_cfg"] = "config file",
                ["f_log"] = "log",
                ["f_readme"] = "manual",
                ["v_none"] = "none",
                // ---- v0.4: running with no window (the ps1's own keys)
                ["st_steam"] = "Steam Among Us",
                ["st_bep"] = "BepInEx",
                ["st_dll"] = "PocketRoles.dll",
                ["st_interop"] = "interop (1st launch)",
                ["st_client"] = "Steam client",
                ["v_unknown"] = "unknown",
                ["v_notfound"] = "not found",
                ["v_ok"] = "OK",
                ["v_pending"] = "not yet",
                ["v_running"] = "running",
                ["v_stopped"] = "not running (start Steam first)",
                ["v_notrunning"] = "not running",
                ["v_needs"] = "(needs update)",
                ["log_mode"] = "Mode: {0}",
                ["mode_dev"] = "developer (source: {0})",
                ["mode_friend"] = "friend (installer)",
                ["log_modded"] = "Modded copy: {0}",
                ["log_steam"] = "Steam copy: {0}",
                ["auto_launch"] = "Playing automatically",
                // ---- v0.4: new in StarPocket Client
                ["st_game"] = "Among Us",
                ["st_play"] = "Play button",
                ["scan_ok"] = "OK  ",
                ["scan_warn"] = "warn",
                ["scan_stop"] = "stop",
                ["cl_unknown"] = "This is not an option of this app: {0}",
                ["cl_extra"] = "This is not written as an option: {0}",
                ["cl_no_value"] = "{0} was given no value.",
                ["cl_two_modes"] = "These cannot be used together: {0}",
                ["cl_twice"] = "This option was given two different values: {0}",
                ["cl_no_launch"] = "{0} only means something when a game is started.",
                ["cl_action_unknown"] = "--action takes install / check / report / status ({0} is not one of them).",
                ["cl_busy"] = "Another StarPocket Client is busy. Wait until it has finished and try again.",
                ["cl_need_consent"] = "You have not agreed to the Terms of Use and the Privacy Policy yet. This job goes online, so open StarPocket Client first and answer the screen it shows you (Terms of Use Article 12(3)). Uninstalling, --action status and --action report work without agreeing.",
                ["cl_running_tray"] = "StarPocket Client is already running in the notification area.",
                ["cl_play_sent"] = "The running StarPocket Client was asked to play.",
                ["cl_play_failed"] = "StarPocket Client is already running, but it could not be asked to play. Open its window and press Play.",
                ["cl_usage"] = "Usage:\r\n"
                    + "  \"StarPocket Client.exe\"                            opens the window\r\n"
                    + "  \"StarPocket Client.exe\" --tray                     no window; the notification area only\r\n"
                    + "  \"StarPocket Client.exe\" --autolaunch [--windowed]  no window; plays at once\r\n"
                    + "  \"StarPocket Client.exe\" --scan-only                one Aegis scan, then it ends\r\n"
                    + "  \"StarPocket Client.exe\" --verify-download          fetches the official file, checks it, and deletes it again\r\n"
                    + "  \"StarPocket Client.exe\" --action install|check|report|status\r\n"
                    + "  \"StarPocket Client.exe\" --uninstall [--quiet]\r\n"
                    + "  Folders and language: --game-dir --steam-dir --desktop-dir --language --friend\r\n"
                    + "  Exit codes: 0 done / 1 failed / 2 --verify-download: the file did not match / 3 --scan-only found a row that stops a start",
                ["hint_continue"] = "  → You can continue. Fix the cause and press again; only this step is redone.",
                ["in_start"] = "=== Install started ===",
                ["in_step1"] = "[1/5] Copying the Steam Among Us...",
                ["in_step2"] = "[2/5] Downloading BepInEx {0}...",
                ["in_step3"] = "[3/5] Fetching the latest PocketRoles...",
                ["in_step4"] = "[4/5] Creating the launch files...",
                ["in_step5"] = "[5/5] Saving state...",
                ["in_steam_found"] = "Steam copy: {0}",
                ["in_steam_notfound"] = "Steam Among Us not found. Please pick the folder that contains Among Us.exe.",
                ["in_pick"] = "Select the folder that contains Among Us.exe (Steam version)",
                ["dev_pick"] = "Select the PocketRoles source folder (the one with PocketRoles.csproj and PocketRolesLauncher.ps1)",
                ["dev_pick_bad"] = "That folder is not the PocketRoles source. Pick the folder that has BOTH PocketRoles.csproj and PocketRolesLauncher.ps1.",
                ["dev_pick_ok"] = "The source folder is now {0}. Developer mode uses it from the next time the app is opened.",
                ["in_copy_skip"] = "Already copied (same version {0}) — skipped",
                ["in_copying"] = "{0} → {1} (about 1 GB, a few minutes)",
                ["in_copy_done"] = "Copy finished ({0} copied, {1} already the same)",
                ["in_copy_fail"] = "Copy failed ({0}).",
                ["in_copy_close"] = "Close the game and Steam, then try again.",
                ["in_toolong"] = "The chosen folder sits too deep. A file's path would be {0} characters and Windows allows {1}. Please pick a shallower place, such as C:\\PocketRoles.",
                ["in_nospace"] = "Not enough room on the drive. {0} is needed and {1} is free.",
                ["in_interrupted"] = "The last unpacking did not finish. BepInEx and the mod are being put back.",
                ["in_dl_refused"] = "The app does not fetch from this address (it is not one of its own): {0}",
                ["in_bep_skip"] = "BepInEx {0} already installed — skipped",
                ["in_bep_other"] = "A different BepInEx is installed ({0}). It will be overwritten with {1}.",
                ["in_dl"] = "Downloading: {0}",
                ["in_cached"] = "Using the already downloaded file: {0}",
                ["in_zip_bad"] = "Unexpected zip content ({1} missing): {0}",
                ["in_bep_fail"] = "Could not download BepInEx. Check your connection and try again.",
                ["in_hash_ok"] = "The downloaded file was checked (BepInEx {0})",
                ["in_hash_bad"] = "The downloaded file is not the one the official site publishes. It was deleted and nothing was put into the game. A connection that broke part-way does this too. Please try again: {0}",
                ["in_hash_detail"] = "File check: expected {0} / got {1}",
                ["in_bep_nohash"] = "This app has no record of the right file for BepInEx {0}. Nothing is downloaded and nothing is unpacked. Please wait for an app update.",
                // ---- "--verify-download" (src\Core\BepVerifier.cs)
                ["vd_start"] = "Fetching one file from the official site and checking it (BepInEx {0}, about 31 MB). Nothing is put into the game folder.",
                ["vd_where"] = "Work folder: {0}",
                ["vd_prog"] = "Receiving... {0}%",
                ["vd_prog_mb"] = "Receiving... {0} MB",
                ["vd_got"] = "Received ({0} bytes): {1}",
                ["vd_ok"] = "Checked. The file the official site served is the one this app has written down (BepInEx {0}). Its contents unpacked too ({1} files). The file and everything unpacked from it have been deleted. Nothing was put into the game folder.",
                ["vd_ng_hash"] = "The file that came down is not the one this app has written down. A connection that broke part-way does this too. Please try again; if it says the same thing again, tell the author before anything is released. The file was deleted and nothing was put into the game folder.",
                ["vd_ng_zip"] = "The file's fingerprint matched, but {0} was not inside it. Tell the author before anything is released. The file was deleted and nothing was put into the game folder.",
                ["vd_ng_expand"] = "The file's fingerprint matched, but unpacking it stopped part-way ({0}). Check the free space on the drive and try again. Nothing was put into the game folder.",
                ["vd_ng_net"] = "The official site could not be reached, so no file came down. Check your connection and try again. Nothing was put into the game folder.",
                ["vd_ng_read"] = "Receiving the file stopped part-way. Check the free space on the drive and your connection, then try again. The full reason is in the record. Nothing was put into the game folder.",
                ["vd_ng_space"] = "The drive ran out of room. Free up 150 MB or more and try again. Nothing was put into the game folder.",
                ["vd_ng_refused"] = "The official site pointed at somewhere this app does not fetch from. No file came down. Tell the author before anything is released. Nothing was put into the game folder.",
                ["vd_ng_temp"] = "The work folder could not be made ({0}). Nothing was put into the game folder.",
                ["vd_temp_taken"] = "a different folder of that name is there already: {0}",
                ["vd_busy"] = "Another check is already running. Please wait for it to finish. Nothing was put into the game folder.",
                ["vd_cleaned"] = "cleared what an earlier run left behind: {0}",
                ["vd_prog_files"] = "Extracting... {0} files",
                ["vd_left"] = "The work files could not be deleted. They are still here: {0}",
                ["vd_seelog"] = "Full record: {0}",
                ["in_extract"] = "Extracting: {0}",
                ["in_extract_done"] = "Extracted ({0} files)",
                ["in_mod_skip"] = "PocketRoles {0} already installed — skipped",
                ["in_mod_local"] = "Using the zip next to the app: {0}",
                ["in_mod_localdir"] = "Using the PocketRoles files extracted next to the app: {0}",
                ["in_mod_norelease"] = "No release published on GitHub yet. Press \"Check for updates\" once it is out.",
                ["in_mod_fail"] = "Could not fetch PocketRoles. Press \"Check for updates\" later to finish the install.",
                ["in_mod_done"] = "PocketRoles {0} installed",
                ["in_done"] = "=== Install complete. Start Steam, then press \"Play\" ===",
                ["in_partial"] = "=== {0} step(s) failed. Fix the cause and press again to resume ===",
                ["up_checking"] = "Checking GitHub for the latest PocketRoles...",
                ["up_latest"] = "Latest: {0} / installed: {1}",
                ["up_uptodate"] = "PocketRoles is up to date ({0})",
                ["up_available"] = "PocketRoles {0} is available (installed: {1}). Press \"Update\" to install it.",
                ["up_available_dev"] = "PocketRoles {0} is available (installed: {1}). Press \"Update\" to install it (the locally built DLL will be overwritten).",
                ["up_same_other_file"] = "The PocketRoles {0} installed here is not the same file as the one we publish. Press \"Update\" to put the official one in.",
                ["up_same_other_file_dev"] = "The PocketRoles {0} installed here is not the same file as the one we publish. Press \"Update\" to put the official one in (the locally built DLL will be overwritten).",
                ["up_done"] = "=== Updated to PocketRoles {0} (config and cosmetics kept) ===",
                ["up_norelease"] = "No release on GitHub yet (404). Try again later.",
                ["up_ratelimit"] = "GitHub API rate limit reached (403). Wait about an hour and try again.",
                ["up_api_fail"] = "Could not reach GitHub: {0}  (you can still play offline)",
                ["up_asset_missing"] = "PocketRoles-<ver>.zip not found in the release: {0}",
                ["sync_start"] = "Copying the Steam game files into the modded copy...",
                ["sync_done"] = "Copy finished; old interop removed. It is regenerated on the next launch (1-2 min). If PocketRoles does not support the new game version yet, press \"Check for updates\".",
                ["la_sync_first"] = "The Steam version was updated ({0} → {1}). \"Update and play\" refreshes the mod copy first, then starts the game.",
                ["al_repair"] = "The mod copy is not complete. Press \"Repair\" to fix it",
                ["al_repair_mod"] = "The PocketRoles file has changed. Press \"Repair\" to install it again",
                ["rp_creating"] = "Creating the report zip...",
                ["rp_done"] = "Created: {0}",
                ["rp_title"] = "Report zip created",
                ["rp_msg"] = "Created on your Desktop:{0}{1}{0}{0}Please e-mail this file as an attachment.{0}  Bugs:     {2}{0}  Requests: {3}{0}{0}The buttons below open your mail app with the subject filled in.",
                ["rp_mail_bug"] = "Open mail (bug)",
                ["rp_mail_req"] = "Open mail (request)",
                ["rp_open"] = "Show zip location",
                ["rp_close"] = "Close",
                ["rp_subject_bug"] = "[PocketRoles] bug report v{0}",
                ["rp_subject_req"] = "[PocketRoles] feature request v{0}",
                ["rp_body"] = "Please attach {0} from your Desktop.{1}{1}* What happened / what you would like:{1}{1}* When (date, time) / room code / player count:{1}{1}* What the other players saw:{1}",
                ["rp_ev"] = "It also holds {0} Aegis evidence record(s) (bans and removals of the last 90 days; the mod deletes evidence records after 90 days, and keeps those of a ban still in force at least until 30 days after it ends; logs go after 30 days, so an older record comes with the 2 log lines that back it): names, room codes, what was detected and the latest log lines about that player (for a callout notice, the first 40 characters of their line). Players are told apart only by a hash of the PUID and their erase code (no friend-code hash, no friend code or PUID itself, no IP address, no other player's chat; PUIDs and friend codes in the logs are masked too).",
                ["rp_ev_none"] = "There were no Aegis evidence records (none included). PUIDs and friend codes in the logs are masked.",
                ["rp_autodelete"] = "This zip is deleted automatically after 30 days (you can delete it as soon as it is sent)",
                ["ex_title"] = "One player's evidence zip",
                ["ex_prompt"] = "To check an appeal, this makes a small zip with the evidence records of one player only (no other player's records; a detection line of their record can name another player of that game).{0}{0}Enter one of these for that player:{0}- their erase code (the 16 letters of /cmd id){0}- their friend code (name#1234){0}- an evidence id (AEG-XXXXX)",
                ["ex_make"] = "Create",
                ["ex_cancel"] = "Cancel",
                ["ex_bad"] = "Not recognized. Enter an erase code (16 letters), a friend code (name#1234) or an evidence id (AEG-XXXXX)",
                ["ex_none"] = "This PC has no evidence record of that player (evidence records are deleted after 90 days; those of a ban still in force stay until 30 days after it ends)",
                ["ex_creating"] = "Creating the zip of that player's evidence...",
                ["ex_done"] = "Created a zip with {0} evidence record(s): {1}",
                ["ex_nolog"] = "No log lines backing {0} of them were found (for example when that game's log is gone; the author's check will show \"does not match its log\")",
                ["ex_msg"] = "Created {1} on your Desktop.{0}{0}It holds only that player's {2} evidence record(s) (those this PC still keeps), the log lines that back them and this PC's own details (system.txt, launcher-state.json). No other player's records or logs are in it (a detection line of their record can name another player of that game - the player who was killed, reported or voted - or the moderator who banned them). Names, room codes and what was detected are in it. The player is told apart only by a hash of the PUID and their erase code; neither the friend code nor its hash is in it (that code ties the appeal to the records; it does not prove who sent it).{0}{0}Please e-mail it to the author at {3} and to nobody else: do not pass it on or post it (play rules, article 7).{0}This zip is deleted automatically after 30 days (you can delete it as soon as it is sent).",
                ["ex_warn"] = "Send this zip to the author ({0}) only: do not pass it on or post it (play rules 7(1)). It holds that player's erase code and the hash of their PUID, which the restriction list uses.",
                ["ex_mail"] = "Open mail",
                ["ex_subject"] = "[PocketRoles] one player's evidence v{0}",
                ["ex_body"] = "Please attach {0} from your Desktop.{1}{1}* Name of the player who appealed / ticket number (if known):{1}",
                ["sc_made"] = "Shortcut created: {0}",
                ["sc_fail"] = "The shortcut could not be created: {0}",
                ["as_on"] = "StarPocket Client opens when Windows starts (waiting in the notification area).",
                ["as_off"] = "StarPocket Client does not open when Windows starts.",
                ["ac_fixed"] = "The text would be hard to read as it was, so the colour was changed a little. Picked: {0} -> used: {1}",
                ["ac_red"] = "Red is the colour that means something went wrong, so the hue was moved a little.",
                ["un_confirm"] = "This removes StarPocket Client from this PC. It removes: the app itself, its settings and records ({0}), the shortcuts the app made, the \"start with Windows\" setting and the Apps & Features entry. It does not remove: Steam or Steam's Among Us, the Aegis records (the current launcher and tray use them), or the report zips on your Desktop (they go by themselves after 30 days).",
                ["un_keep_mod"] = "The mod's copy of the game (about 1 GB, with your settings and records in it) is kept. Tick the box to remove it as well.",
                ["un_done"] = "Removed. The window will close.",
                ["un_closing"] = "Uninstalling. The files go once this window has closed.",
                ["un_partial"] = "{0} item(s) could not be removed. Close the game and File Explorer, then try again.",
                ["un_stopped"] = "The app's own records folder could not be removed, so nothing else was touched (nothing was deleted). Please try again: {0}",
                ["un_running"] = "StarPocket Client is running. Close it, then uninstall again.",
                ["un_leftfolder"] = "This app's files are in this folder, where you put them yourself. Remove it if you do not want it: {0}",
                ["un_title"] = "Uninstall StarPocket Client?",
                ["un_del_mod"] = "Remove the mod's copy of the game as well",
                ["un_yes"] = "Uninstall",
                ["un_left"] = "Still there: {0}",
                ["un_selffolder"] = "A running app cannot delete itself, so please remove this folder by hand after it closes: {0}",
                // ---- v0.4: developer mode's "Rebuild only" and "Check / update"
                ["sdk_missing"] = ".NET SDK not found: {0}",
                ["dev_only"] = "This is only available in developer mode (switched on in Settings → PocketRoles → Developer, or when the app is started from the folder that has PocketRoles.csproj).",
                // ---- v1.1: the developer switch (Settings → PocketRoles → Developer) and which DLL is in the copy
                ["dev_nofolder"] = "The developer folder was not found (the folder the Desktop's PocketRoles.lnk points to, or Desktop\\HostRoles, holding both PocketRoles.csproj and PocketRolesLauncher.ps1).",
                ["dev_switch_on"] = "Switching to the developer build. StarPocket Client will reopen.",
                ["dev_switch_off"] = "Back to the released build (friend mode). StarPocket Client will reopen.",
                ["origin_dev"] = "developer build (rebuilt {0})",
                ["origin_release"] = "release {0} (installed {1})",
                ["origin_unknown"] = "put there by something other than this client (e.g. a rebuild by the old launcher)",
                ["dev_building"] = "Building PocketRoles (1-2 minutes)...",
                ["dev_build_done"] = "Build succeeded. PocketRoles.dll is in BepInEx\\plugins.",
                ["dev_build_ok"] = "The build has finished.",
                ["dev_build_failed"] = "The build failed.",
                ["dev_build_timeout"] = "The build had still not finished after {0} minutes, so it was stopped.",
                ["dev_build_failed_exit"] = "Build failed (exit {0}). The game's API may have changed.",
                ["dev_build_ask"] = "Send the errors to Claude and ask it to make PocketRoles work with the new version.",
                ["dev_need_steam"] = "Start Steam before updating (the game has to run to write the interop files).",
                ["dev_up_start"] = "=== Update started ===",
                ["dev_up_1"] = "[1/4] Copying the Steam version's game files into the mod copy...",
                ["dev_up_2"] = "[2/4] Removing the old interop / cache...",
                ["dev_up_3"] = "[3/4] Starting the game to write the interop files (1-3 minutes; it closes by itself)...",
                ["dev_up_4"] = "[4/4] Rebuilding PocketRoles...",
                ["dev_interop_failed"] = "No interop files were written. Please look at BepInEx\\LogOutput.log.",
                ["dev_interop_ok"] = "The interop files are ready.",
                ["dev_up_done"] = "=== Update finished. Play with \"Start with the mod\" ===",
                ["tray.open"] = "Open",
                ["tray.play"] = "Play",
                ["tray.aegis"] = "Aegis status",
                ["tray.rescan"] = "Scan again",
                ["tray.quit"] = "Quit",
                ["tip.idle"] = "StarPocket Client — Aegis standing by",
                ["tip.watching"] = "StarPocket Client — Aegis watching · {0} flagged · {1} removed",
                ["tip.off"] = "StarPocket Client — Aegis off",
                ["tip.serious"] = "StarPocket Client — Aegis found a problem",
                ["tip.oldtray"] = "StarPocket Client — the old Aegis tray is watching",
                ["tray.stillRunning"] = "Still running in the notification area at the bottom right of the screen. To quit, right-click its icon and choose Quit.",
                ["quit.confirm"] = "Quitting also stops Aegis from watching the rest of this game. Quit?",
                ["badge.serious"] = "Aegis found a problem",
                ["badge.kicked"] = "Aegis removed a player",
                ["wv2.head"] = "Install the WebView2 Runtime",
                ["wv2.body"] = "StarPocket Client draws its window with this Microsoft component. On the page that opens, download the “Evergreen Bootstrapper”, run the downloaded file to install it, then press “Check again”.",
                ["wv2.old"] = "The current launcher (PocketRoles Launcher.cmd) still works.",
                ["wv2.open"] = "Open the download page",
                ["wv2.retry"] = "Check again",
                ["wv2.notyet"] = "Still not found. Press it again once the installation has finished.",
                ["wv2.close"] = "Close",
                ["files.missing"] = "Some StarPocket Client files are missing. Extract everything in the zip into one folder, then open it again (the exe alone does not work).",
                ["ui.failed"] = "Could not open the window: {0}",
                // ---- v1.3: the icon picture (src\Core\ProfileImage.cs)
                ["av_pick"] = "Choose a picture for your icon",
                ["av_filter"] = "Images (*.png;*.jpg;*.jpeg;*.ico;*.bmp;*.gif)|*.png;*.jpg;*.jpeg;*.ico;*.bmp;*.gif",
                ["av_toobig"] = "That picture is too large ({0}). Please choose one of 20 MB or less",
                ["av_toomany"] = "That picture has too many pixels ({0}×{1}). Please choose one of 30 million pixels or less",
                ["av_unreadable"] = "That picture could not be read (it is damaged, or in a format this app does not know). The built-in icon stays",
                ["av_webp"] = "This version cannot read WebP. Please convert it to PNG or JPG first",
                ["av_nofile"] = "That file could not be opened (the location cannot be read, or the file is gone)",
                ["av_write"] = "The copy of the picture could not be saved: {0}",
                ["av_broken"] = "The saved icon picture could not be read, so the built-in icon is back",
                ["av_set"] = "Icon picture taken in ({0}×{1} → 256×256)",
                ["av_cleared"] = "Icon picture removed; the built-in icon is back",
            },
        };

        /// <summary>The launcher logs this line in Japanese whatever the language (ps1: Invoke-Launch, -Windowed).</summary>
        public const string WindowedLaunchLog = "ウィンドウモード (1600x900) で起動しました";

        /// <summary>Like the ps1's T: the language's text, else Japanese, else the key; {0}.. filled (a bad format gives the raw text).</summary>
        public static string T(string lang, string key, params object[] args)
        {
            string s = null;
            Dictionary<string, string> tbl;
            if (lang != null && Table.TryGetValue(lang, out tbl)) tbl.TryGetValue(key, out s);
            if (string.IsNullOrEmpty(s)) Table["ja"].TryGetValue(key, out s);
            if (string.IsNullOrEmpty(s)) return key;
            if (args != null && args.Length > 0)
            {
                try { return string.Format(s, args); }
                catch (FormatException) { return s; }
            }
            return s;
        }
    }
}
